const CREDS={uid:"Nexova",pass:"Sajid001188"};
let products=JSON.parse(localStorage.getItem("nexova_products")||"null")||[];
function money(n){return "৳"+Number(n).toLocaleString("en-BD")}
function login(){if(document.getElementById("uid").value===CREDS.uid&&document.getElementById("pass").value===CREDS.pass){sessionStorage.setItem("nx_admin","1");showDashboard()}else alert("Invalid User ID or Password")}
function showDashboard(){document.getElementById("login").classList.add("hidden");document.getElementById("dashboard").classList.remove("hidden");refresh()}
function logout(){sessionStorage.removeItem("nx_admin");location.reload()}
if(sessionStorage.getItem("nx_admin")==="1")showDashboard();
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function showTab(id){document.querySelectorAll(".tab-page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id));document.getElementById("pageTitle").textContent=id[0].toUpperCase()+id.slice(1);if(id==="orders")renderOrders()}
function refresh(){products=JSON.parse(localStorage.getItem("nexova_products")||"[]");document.getElementById("statProducts").textContent=products.length;const orders=JSON.parse(localStorage.getItem("nexova_orders")||"[]");document.getElementById("statOrders").textContent=orders.length;document.getElementById("statPending").textContent=orders.length;document.getElementById("statSales").textContent=money(orders.reduce((s,o)=>s+Number(o.total||0),0));renderProducts();renderOrders()}
function renderProducts(){document.getElementById("adminProducts").innerHTML=products.map(p=>`<div class="admin-card"><div class="thumb">${p.image?`<img src="${p.image}">`:p.icon||"✦"}</div><h4>${p.name}</h4><div class="prices">${money(p.price)} ${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:""}</div><div class="admin-actions"><button onclick="editProduct(${p.id})">Edit</button><button class="delete" onclick="deleteProduct(${p.id})">Delete</button></div></div>`).join("")}
function openEditor(id=null){document.getElementById("editor").classList.add("open");document.getElementById("editorTitle").textContent=id?"Edit Product":"Add Product";document.getElementById("pid").value=id||"";const p=products.find(x=>x.id===id);document.getElementById("pname").value=p?.name||"";document.getElementById("pprice").value=p?.price||"";document.getElementById("pold").value=p?.oldPrice||"";document.getElementById("pcat").value=p?.category||"perfumes";document.getElementById("ptags").value=p?.tags?.join(",")||"";document.getElementById("pdesc").value=p?.desc||"";document.getElementById("pimage").value=p?.image||""}
function closeEditor(){document.getElementById("editor").classList.remove("open")}
function saveProduct(){const id=document.getElementById("pid").value;const data={id:id?Number(id):Date.now(),name:document.getElementById("pname").value.trim(),price:Number(document.getElementById("pprice").value),oldPrice:Number(document.getElementById("pold").value)||0,category:document.getElementById("pcat").value,tags:document.getElementById("ptags").value.split(",").map(x=>x.trim()).filter(Boolean),desc:document.getElementById("pdesc").value.trim(),image:document.getElementById("pimage").value.trim(),icon:"✦"};if(!data.name||!data.price){alert("Product name and price are required.");return}if(id)products=products.map(p=>p.id===Number(id)?data:p);else products.unshift(data);localStorage.setItem("nexova_products",JSON.stringify(products));closeEditor();refresh()}
function editProduct(id){openEditor(id)}
function deleteProduct(id){if(confirm("Delete this product?")){products=products.filter(p=>p.id!==id);localStorage.setItem("nexova_products",JSON.stringify(products));refresh()}}
function renderOrders(){const orders=JSON.parse(localStorage.getItem("nexova_orders")||"[]");document.getElementById("ordersList").innerHTML=orders.length?orders.map(o=>{const names=o.items.map(i=>{const p=products.find(x=>x.id===i.id);return `${p?.name||"Deleted product"} ×${i.qty}`}).join(" • ");return `<div class="order"><div class="order-head"><div><b>${o.id}</b><small> · ${new Date(o.date).toLocaleString()}</small></div><span class="status">${o.payment}</span></div><div class="order-items">${names}</div><small>${o.name} · ${o.phone} · ${o.address}</small><div style="margin-top:10px;color:#f0cb72">Total: ${money(o.total)}</div></div>`}).join(""):`<div class="panel">No orders yet.</div>`}
function exportOrders(){const orders=JSON.parse(localStorage.getItem("nexova_orders")||"[]");const rows=[["Order","Date","Name","Phone","Address","Payment","Total"],...orders.map(o=>[o.id,o.date,o.name,o.phone,o.address,o.payment,o.total])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="nexova-orders.csv";a.click()}
function saveSettings(){localStorage.setItem("nexova_wa",document.getElementById("waSetting").value);alert("Settings saved in this browser.")}
